Tutorial 02

1. Re-do Tutorial 1 assignment with numpy. (This should be fairly easy, but use only numpy functions to reproduce your results)
2. Use the data from Beehive_data.csv to find the distance to the Beehive Cluster. Read on ahead to find out more about the concepts in astronomy you will need to solve this.

Solution to Tutorial 02

In [144]:
import numpy as np

In [145]:
moons = np.loadtxt("Moons_and_planets.csv", delimiter=",", dtype=str)
print(moons)
print(len(moons))

[['Moon' 'Earth' '1737.1']
 ['Phobos' 'Mars' '11.1']
 ['Deimos' 'Mars' '6.2']
 ['Io' 'Jupiter' '1818.1']
 ['Europa' 'Jupiter' '1560.7']
 ['Ganymede' 'Jupiter' '2634.1']
 ['Callisto' 'Jupiter' '2408.4']
 ['Amalthea' 'Jupiter' '83.5']
 ['Himalia' 'Jupiter' '67.0']
 ['Elara' 'Jupiter' '43.0']
 ['Pasiphae' 'Jupiter' '30.0']
 ['Sinope' 'Jupiter' '19.0']
 ['Lysithea' 'Jupiter' '18.0']
 ['Carme' 'Jupiter' '23.0']
 ['Ananke' 'Jupiter' '14.0']
 ['Leda' 'Jupiter' '10.0']
 ['Thebe' 'Jupiter' '49.3']
 ['Adrastea' 'Jupiter' '8.2']
 ['Metis' 'Jupiter' '21.5']
 ['Callirrhoe' 'Jupiter' '4.3']
 ['Themisto' 'Jupiter' '4.0']
 ['Megaclite' 'Jupiter' '2.7']
 ['Taygete' 'Jupiter' '2.5']
 ['Chaldene' 'Jupiter' '1.9']
 ['Harpalyke' 'Jupiter' '2.2']
 ['Kalyke' 'Jupiter' '2.6']
 ['Iocaste' 'Jupiter' '2.6']
 ['Erinome' 'Jupiter' '1.6']
 ['Isonoe' 'Jupiter' '1.9']
 ['Praxidike' 'Jupiter' '3.4']
 ['Autonoe' 'Jupiter' '2.0']
 ['Thyone' 'Jupiter' '2.0']
 ['Hermippe' 'Jupiter' '2.0']
 ['Aitne' 'Jupiter' '1.5']
 ['Eur

In [146]:
planets = np.copy(moons)
print(planets[:,1])
print(len(planets[:,1]))

['Earth' 'Mars' 'Mars' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter'
 'Jupiter' 'Jupiter' 'Jupiter' 'Jupiter' 'Saturn' 'Saturn' 'Saturn'
 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn'
 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn' 'Saturn'
 'S

In [147]:
count1 = 0
for planet in planets:
    if 'Mercury' in planet:
        count1 = count1 + 1

count2 = 0
for planet in planets:
    if 'Venus' in planet:
        count2 = count2 + 1

count3 = 0
for planet in planets:
    if 'Earth' in planet:
        count3 = count3 + 1

count4 = 0
for planet in planets:
    if 'Mars' in planet:
        count4 = count4 + 1

count5 = 0
for planet in planets:
    if 'Jupiter' in planet:
        count5 = count5 + 1

count6 = 0
for planet in planets:
    if 'Saturn' in planet:
        count6 = count6 + 1

count7 = 0
for planet in planets:
    if 'Uranus' in planet:
        count7 = count7 + 1

count8 = 0
for planet in planets:
    if 'Neptune' in planet:
        count8 = count8 + 1

count9 = 0
for planet in planets:
    if 'Pluto' in planet:
        count9 = count9 + 1

print('The number of moons of each planet are as follows:')
print('Mercury:', count1)
print('Venus:', count2)
print('Earth:', count3)
print('Mars:', count4)
print('Jupiter:', count5)
print('Saturn:', count6)
print('Uranus:', count7)
print('Neptune:', count8)
print('Pluto:', count9)

The number of moons of each planet are as follows:
Mercury: 0
Venus: 0
Earth: 1
Mars: 2
Jupiter: 79
Saturn: 82
Uranus: 27
Neptune: 14
Pluto: 5


---------------------------------------------------------------------------------------------------------------------------------------------

Part 1

Exclude all the stars with low probability of belonging to the cluster, and then calculate distance for each star, and find the mean.

In [148]:
Beehive_data = np.loadtxt("Beehive_data.csv", delimiter = ",")
print(Beehive_data)
print(len(Beehive_data))

[[ 6.300e+00  1.770e+00  1.000e+02]
 [ 6.390e+00  1.850e+00  1.000e+02]
 [ 6.440e+00  1.850e+00  1.000e+02]
 [ 6.590e+00  1.760e+00  1.000e+02]
 [ 6.610e+00  1.720e+00  3.500e+01]
 [ 6.610e+00  1.720e+00  4.700e+01]
 [ 6.610e+00  1.720e+00  1.700e+01]
 [ 6.670e+00  1.620e+00  1.000e+02]
 [ 6.780e+00  1.570e+00  1.000e+02]
 [ 6.780e+00  1.580e+00  1.000e+02]
 [ 6.850e+00  1.550e+00  1.000e+02]
 [ 6.900e+00  1.640e+00  1.000e+02]
 [ 7.320e+00  1.360e+00  1.000e+02]
 [ 7.450e+00  1.310e+00  1.000e+02]
 [ 7.540e+00  1.270e+00  1.000e+02]
 [ 7.540e+00  1.280e+00  4.300e+01]
 [ 7.540e+00  1.280e+00  2.700e+01]
 [ 7.540e+00  1.280e+00  3.000e+01]
 [ 7.670e+00  1.220e+00  4.300e+01]
 [ 7.670e+00  1.220e+00  2.400e+01]
 [ 7.670e+00  1.220e+00  3.300e+01]
 [ 7.700e+00  1.210e+00  4.300e+01]
 [ 7.700e+00  1.210e+00  2.400e+01]
 [ 7.700e+00  1.210e+00  3.300e+01]
 [ 7.730e+00  1.200e+00  1.000e+02]
 [ 7.960e+00  1.110e+00  1.000e+02]
 [ 8.020e+00  1.080e+00  1.000e+02]
 [ 8.180e+00  1.010e+00  1.0

In [149]:
Beehive_data_rounded = np.round(Beehive_data,1)
print(Beehive_data_rounded)
print(len(Beehive_data_rounded))

[[  6.3   1.8 100. ]
 [  6.4   1.8 100. ]
 [  6.4   1.8 100. ]
 [  6.6   1.8 100. ]
 [  6.6   1.7  35. ]
 [  6.6   1.7  47. ]
 [  6.6   1.7  17. ]
 [  6.7   1.6 100. ]
 [  6.8   1.6 100. ]
 [  6.8   1.6 100. ]
 [  6.8   1.6 100. ]
 [  6.9   1.6 100. ]
 [  7.3   1.4 100. ]
 [  7.4   1.3 100. ]
 [  7.5   1.3 100. ]
 [  7.5   1.3  43. ]
 [  7.5   1.3  27. ]
 [  7.5   1.3  30. ]
 [  7.7   1.2  43. ]
 [  7.7   1.2  24. ]
 [  7.7   1.2  33. ]
 [  7.7   1.2  43. ]
 [  7.7   1.2  24. ]
 [  7.7   1.2  33. ]
 [  7.7   1.2 100. ]
 [  8.    1.1 100. ]
 [  8.    1.1 100. ]
 [  8.2   1.  100. ]
 [  8.3   1.  100. ]
 [  8.3   1.  100. ]
 [  8.5   0.9 100. ]
 [  8.7   0.8 100. ]
 [  8.8   0.8 100. ]
 [  8.9   0.7 100. ]
 [  9.    0.7 100. ]
 [  9.    0.7 100. ]
 [  9.2   0.6 100. ]
 [  9.3   0.6  62. ]
 [  9.3   0.6   9. ]
 [  9.3   0.6  30. ]
 [  9.4   0.6 100. ]
 [  9.4   0.5 100. ]
 [  9.4   0.5 100. ]
 [  9.6   0.5 100. ]
 [  9.6   0.5 100. ]
 [  9.7   0.4 100. ]
 [  9.7   0.4 100. ]
 [  9.8   0.4

In [150]:
low_prob = np.where(Beehive_data_rounded[:,2]<50)
Beehive_data_updated = np.delete(Beehive_data_rounded,low_prob,axis=0)
print(Beehive_data_updated)
print(len(Beehive_data_updated))

[[  6.3   1.8 100. ]
 [  6.4   1.8 100. ]
 [  6.4   1.8 100. ]
 [  6.6   1.8 100. ]
 [  6.7   1.6 100. ]
 [  6.8   1.6 100. ]
 [  6.8   1.6 100. ]
 [  6.8   1.6 100. ]
 [  6.9   1.6 100. ]
 [  7.3   1.4 100. ]
 [  7.4   1.3 100. ]
 [  7.5   1.3 100. ]
 [  7.7   1.2 100. ]
 [  8.    1.1 100. ]
 [  8.    1.1 100. ]
 [  8.2   1.  100. ]
 [  8.3   1.  100. ]
 [  8.3   1.  100. ]
 [  8.5   0.9 100. ]
 [  8.7   0.8 100. ]
 [  8.8   0.8 100. ]
 [  8.9   0.7 100. ]
 [  9.    0.7 100. ]
 [  9.    0.7 100. ]
 [  9.2   0.6 100. ]
 [  9.3   0.6  62. ]
 [  9.4   0.6 100. ]
 [  9.4   0.5 100. ]
 [  9.4   0.5 100. ]
 [  9.6   0.5 100. ]
 [  9.6   0.5 100. ]
 [  9.7   0.4 100. ]
 [  9.7   0.4 100. ]
 [  9.8   0.4 100. ]
 [  9.8   0.4 100. ]
 [  9.8   0.4 100. ]
 [  9.8   0.4 100. ]
 [  9.9   0.4 100. ]
 [  9.9   0.4 100. ]
 [ 10.    0.3  66. ]
 [ 10.1   0.3 100. ]
 [ 10.1   0.3 100. ]
 [ 10.1   0.3 100. ]
 [ 10.2   0.2 100. ]
 [ 10.2   0.2 100. ]
 [ 10.3   0.2 100. ]
 [ 10.3   0.2 100. ]
 [ 10.3   0.2

In [151]:
def distance_to_Beehive(Beehive_data_updated):
    power_raise_to_10 = ((Beehive_data_updated[:,0] + 2.5*(Beehive_data_updated[:,1]) + 0.17)/5)
    d = 10**power_raise_to_10
    return d
    
result = distance_to_Beehive(Beehive_data_updated)
print(result)
print(len(result))

[156.31476426 163.68165214 163.68165214 179.47336268 149.27944096
 156.31476426 156.31476426 156.31476426 163.68165214 156.31476426
 145.88142603 152.75660582 149.27944096 152.75660582 152.75660582
 149.27944096 156.31476426 156.31476426 152.75660582 149.27944096
 156.31476426 145.88142603 152.75660582 152.75660582 149.27944096
 156.31476426 163.68165214 145.88142603 145.88142603 159.95580286
 159.95580286 149.27944096 149.27944096 156.31476426 156.31476426
 156.31476426 156.31476426 163.68165214 163.68165214 152.75660582
 159.95580286 159.95580286 159.95580286 149.27944096 149.27944096
 156.31476426 156.31476426 156.31476426 163.68165214 152.75660582
 149.27944096 149.27944096 149.27944096 149.27944096 163.68165214
 163.68165214 171.39573075 152.75660582 152.75660582 152.75660582
 156.31476426 179.47336268 159.95580286 167.4942876  183.65383433
 179.47336268 159.95580286 179.47336268 167.4942876  167.4942876
 163.68165214 171.39573075 179.47336268 179.47336268 187.93168168
 167.494287

In [152]:
result_rounded = np.round(result,3)
print(result_rounded)
print(len(result_rounded))

[156.315 163.682 163.682 179.473 149.279 156.315 156.315 156.315 163.682
 156.315 145.881 152.757 149.279 152.757 152.757 149.279 156.315 156.315
 152.757 149.279 156.315 145.881 152.757 152.757 149.279 156.315 163.682
 145.881 145.881 159.956 159.956 149.279 149.279 156.315 156.315 156.315
 156.315 163.682 163.682 152.757 159.956 159.956 159.956 149.279 149.279
 156.315 156.315 156.315 163.682 152.757 149.279 149.279 149.279 149.279
 163.682 163.682 171.396 152.757 152.757 152.757 156.315 179.473 159.956
 167.494 183.654 179.473 159.956 179.473 167.494 167.494 163.682 171.396
 179.473 179.473 187.932 167.494 179.473 187.932 242.103]
79


In [153]:
distance_to_Beehive_cluster = result.mean()
print(distance_to_Beehive_cluster)

160.62077832451328


In [154]:
distance_to_Beehive_cluster = result_rounded.mean()
print(np.round(distance_to_Beehive_cluster,3))

160.621


In [155]:
sum_of_dist = 0
for d in result_rounded:
    sum_of_dist = sum_of_dist + d
distance_to_Beehive = sum_of_dist/result_rounded.size
print(distance_to_Beehive)
print(np.round(distance_to_Beehive,3))

160.62082278481023
160.621


---------------------------------------------------------------------------------------------------------------------------------------------

Part 2

Find the distance for all stars (including the low probability ones) and find the weighted average of the distances, where the weights are the probability.

In [156]:
def distance_to_Beehive(Beehive_data):
    power_raise_to_10 = ((Beehive_data[:,0] + 2.5*(Beehive_data[:,1]) + 0.17)/5)
    d = 10**power_raise_to_10
    return d
    
result = distance_to_Beehive(Beehive_data)
print(result)
print(len(result))

[151.00801542 172.5837892  176.60378207 170.6082389  164.43717232
 164.43717232 164.43717232 150.66070662 149.62356561 151.35612484
 151.00801542 171.39573075 150.66070662 151.00801542 150.31419661
 152.05475297 152.05475297 152.05475297 150.66070662 150.66070662
 150.66070662 151.00801542 151.00801542 151.00801542 151.35612484
 151.70503675 150.66070662 149.62356561 149.96848355 151.35612484
 151.00801542 149.96848355 149.96848355 150.31419661 151.00801542
 150.31419661 151.35612484 153.46169828 153.46169828 153.46169828
 152.40527538 152.05475297 152.40527538 152.75660582 152.05475297
 152.40527538 151.35612484 152.40527538 153.81546403 153.10874617
 152.75660582 153.10874617 153.81546403 155.238701   155.238701
 155.238701   153.10874617 153.46169828 153.46169828 153.10874617
 155.59656316 154.52544395 154.52544395 157.03628043 157.03628043
 157.03628043 155.238701   155.95525028 155.238701   155.59656316
 158.12480393 155.95525028 157.76112697 156.67510701 162.55487558
 159.5879147

---------------------------------------------------------------------------------------------------------------------------------------------

Not the correct approach but might be useful.

In [157]:
data = np.copy(Beehive_data_rounded)
v_mag_and_log_l = np.delete(data,2,axis=1)
print(v_mag_and_log_l)
print(len(v_mag_and_log_l))

[[ 6.3  1.8]
 [ 6.4  1.8]
 [ 6.4  1.8]
 [ 6.6  1.8]
 [ 6.6  1.7]
 [ 6.6  1.7]
 [ 6.6  1.7]
 [ 6.7  1.6]
 [ 6.8  1.6]
 [ 6.8  1.6]
 [ 6.8  1.6]
 [ 6.9  1.6]
 [ 7.3  1.4]
 [ 7.4  1.3]
 [ 7.5  1.3]
 [ 7.5  1.3]
 [ 7.5  1.3]
 [ 7.5  1.3]
 [ 7.7  1.2]
 [ 7.7  1.2]
 [ 7.7  1.2]
 [ 7.7  1.2]
 [ 7.7  1.2]
 [ 7.7  1.2]
 [ 7.7  1.2]
 [ 8.   1.1]
 [ 8.   1.1]
 [ 8.2  1. ]
 [ 8.3  1. ]
 [ 8.3  1. ]
 [ 8.5  0.9]
 [ 8.7  0.8]
 [ 8.8  0.8]
 [ 8.9  0.7]
 [ 9.   0.7]
 [ 9.   0.7]
 [ 9.2  0.6]
 [ 9.3  0.6]
 [ 9.3  0.6]
 [ 9.3  0.6]
 [ 9.4  0.6]
 [ 9.4  0.5]
 [ 9.4  0.5]
 [ 9.6  0.5]
 [ 9.6  0.5]
 [ 9.7  0.4]
 [ 9.7  0.4]
 [ 9.8  0.4]
 [ 9.8  0.4]
 [ 9.8  0.4]
 [ 9.8  0.4]
 [ 9.9  0.4]
 [ 9.9  0.4]
 [10.   0.3]
 [10.   0.3]
 [10.   0.3]
 [10.1  0.3]
 [10.1  0.3]
 [10.1  0.3]
 [10.2  0.2]
 [10.2  0.2]
 [10.3  0.2]
 [10.3  0.2]
 [10.3  0.2]
 [10.3  0.2]
 [10.3  0.2]
 [10.4  0.2]
 [10.5  0.1]
 [10.7  0. ]
 [10.7  0. ]
 [10.7  0. ]
 [10.7  0. ]
 [10.9 -0. ]
 [10.9 -0. ]
 [11.  -0. ]
 [11.  -0.1]
 [11.  -0.1]

In [158]:
data = np.copy(Beehive_data_rounded)
log_l_and_prob = np.delete(data,0,axis=1)
prob = np.delete(log_l_and_prob,0,axis=1)
print(prob)

[[100.]
 [100.]
 [100.]
 [100.]
 [ 35.]
 [ 47.]
 [ 17.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [ 43.]
 [ 27.]
 [ 30.]
 [ 43.]
 [ 24.]
 [ 33.]
 [ 43.]
 [ 24.]
 [ 33.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [ 62.]
 [  9.]
 [ 30.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [ 66.]
 [  8.]
 [ 26.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [ 77.]
 [  6.]
 [ 18.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [  0.]
 [  0.]
 [100.]
 [100.]
 [100.]
 [  0.]
 [100.]
 [  0.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [  0.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [  0.]
 [100.]
 [100.]
 [  0.]
 [100.]]


In [159]:
weighted_average = np.average(v_mag_and_log_l, weights=prob)
print(weighted_average)

TypeError: Axis must be specified when shapes of a and weights differ.

---------------------------------------------------------------------------------------------------------------------------------------------

In [160]:
weighted_terms = result*Beehive_data_rounded[:,2]
print(weighted_terms)

[15100.80154164 17258.3789199  17660.37820686 17060.82389003
  5755.30103125  7728.54709911  2795.43192947 15066.07066187
 14962.35656094 15135.61248436 15100.80154164 17139.57307508
 15066.07066187 15100.80154164 15031.4196609   6538.35437785
  4105.47833028  4561.6425892   6478.4103846   3615.85695885
  4971.80331842  6493.34466291  3624.19236999  4983.26450874
 15135.61248436 15170.50367459 15066.07066187 14962.35656094
 14996.84835502 15135.61248436 15100.80154164 14996.84835502
 14996.84835502 15031.4196609  15100.80154164 15031.4196609
 15135.61248436  9514.62529336  1381.15528452  4603.8509484
 15240.52753797 15205.47529732 15240.52753797 15275.66058238
 15205.47529732 15240.52753797 15135.61248436 15240.52753797
 15381.54640303 15310.87461682 15275.66058238 15310.87461682
 15381.54640303 10245.75426572  1241.90960797  4036.20622589
 15310.87461682 15346.16982799 15346.16982799 15310.87461682
 15559.65631605 15452.54439538 15452.54439538 12091.79359337
   942.2176826   2826.6530

In [161]:
sum_of_weighted_terms = 0
for term in weighted_terms:
    sum_of_weighted_terms = sum_of_weighted_terms + term
print(sum_of_weighted_terms)

1324394.7357052034


In [162]:
sum_of_terms = 0
for term in prob:
    sum_of_terms = sum_of_terms + term
print(sum_of_terms)

[8301.]


In [163]:
weighted_average = sum_of_weighted_terms/sum_of_terms
print(weighted_average)

[159.54640835]
