Tutorial 03

Your task is the following:

1. Compute the distance to a galaxy, in suitable units, given the galaxy's serial number.

2. Compute the number of galaxies observed by SDSS-MaNGA, in some given distance interval.

3. Compute the physical separation between two galaxies, given their serial numbers. Note: The two galaxies might be at different radial distances.

Part 1

In [88]:
import numpy as np

In [99]:
galaxies = np.loadtxt("galaxies.csv", delimiter = ",")
serial_number, RA, Dec, redshift = np.genfromtxt("galaxies.csv", delimiter = ",", unpack = True)
#print(galaxies)
print(np.round(galaxies,5))
print(len(galaxies))
print(RA)

[[1.0000000e+00 1.3337110e+02 5.7598430e+01 3.9520000e-02]
 [2.0000000e+00 1.3368567e+02 5.7480250e+01 4.1060000e-02]
 [3.0000000e+00 1.3601717e+02 5.7092330e+01 4.6570000e-02]
 ...
 [4.6540000e+03 2.2807332e+02 2.9657210e+01 6.9020000e-02]
 [4.6550000e+03 2.2704141e+02 2.9222190e+01 1.1130000e-01]
 [4.6560000e+03 2.2817638e+02 2.7799560e+01 6.8650000e-02]]
4656
[133.3711  133.68567 136.01717 ... 228.07332 227.04141 228.17638]


In [108]:
def distance_to_galaxy(galaxies):
    d = (redshift*4285.7)
    return d
dist_to_gal = distance_to_galaxy(galaxies)
print(dist_to_gal)
print(len(distance_to_galaxy(galaxies)))
print(max(dist_to_gal))

[169.35036121 175.95286777 199.58946327 ... 295.80689969 476.98619575
 294.21936927]
4656
1192.211625948


In [91]:
print(f"The distance to the galaxy with serial number {serial_number[4655]} is {dist_to_gal[4655]:5.2f} Mpc.")
#:5.2f is for string formatting

The distance to the galaxy with serial number 4656.0 is 294.22 Mpc.


---------------------------------------------------------------------------------------------------------------------------------------------

Part 2

Compute the number of galaxies observed by SDSS-MaNGA, in some given distance interval.

In [92]:
gal_with_dist = np.concatenate((galaxies, dist_to_gal.reshape(4656,1)), axis=1)
gal_with_dist_final = np.round(gal_with_dist,4)
print(gal_with_dist_final)
print(len(gal_with_dist_final))

[[1.000000e+00 1.333711e+02 5.759840e+01 3.950000e-02 1.693504e+02]
 [2.000000e+00 1.336857e+02 5.748020e+01 4.110000e-02 1.759529e+02]
 [3.000000e+00 1.360172e+02 5.709230e+01 4.660000e-02 1.995895e+02]
 ...
 [4.654000e+03 2.280733e+02 2.965720e+01 6.900000e-02 2.958069e+02]
 [4.655000e+03 2.270414e+02 2.922220e+01 1.113000e-01 4.769862e+02]
 [4.656000e+03 2.281764e+02 2.779960e+01 6.870000e-02 2.942194e+02]]
4656


In [93]:
f = gal_with_dist_final[:,4]
for d in f:
    print(d)

169.3504
175.9529
199.5895
61.5026
198.8831
111.0069
110.3085
170.2859
110.6797
174.6342
133.1474
511.59
112.6302
175.4972
289.6286
173.0684
346.124
88.9959
247.8693
174.7904
81.3271
277.6152
81.3378
81.9642
78.0068
474.7481
1192.2116
98.1148
133.6262
120.7281
79.6177
322.6733
174.6836
393.6985
265.8885
122.7864
128.8743
125.1377
327.8641
124.7801
137.7398
288.5864
119.6214
123.7138
131.9067
115.4499
114.6601
119.8044
127.2362
139.8755
125.7541
72.8526
170.3809
307.6242
185.8023
126.6439
73.1885
73.7648
585.3884
126.9137
302.4926
305.2939
74.9726
555.5833
579.8852
346.9306
121.9277
176.334
157.1511
101.6625
503.1392
119.5753
316.5239
100.618
134.9583
156.7599
114.8898
155.3626
158.0383
134.2552
111.1057
120.6798
109.7599
158.1243
110.7625
155.0773
161.0177
162.9514
110.1456
101.589
169.1375
164.7051
472.4945
159.4715
130.6291
165.757
103.8585
365.1821
154.0694
365.6798
166.332
371.2551
135.6888
128.2629
107.1682
99.1939
128.0152
469.9984
157.4328
464.8258
128.0676
175.0446
102.5202
97.

In [94]:
gal_with_dist_final_sort = np.sort(gal_with_dist_final[:,4])
for d in gal_with_dist_final_sort:
    print(d)
#print(gal_with_dist_final_sort)
print(len(gal_with_dist_final_sort))

2.7196
3.2649
7.1401
10.3293
21.8896
21.9492
33.3422
45.415
47.2844
47.8193
49.8763
49.9096
51.1462
51.7706
53.2673
54.4508
54.7377
54.9422
55.4385
55.5578
55.577
55.6255
56.3976
56.4115
56.416
56.8824
58.3737
58.3852
58.693
58.7574
58.8174
59.214
59.5293
60.0169
60.3293
60.5542
60.6924
60.8488
60.8555
61.5026
61.5411
61.8198
61.9056
62.3207
62.6857
62.7884
63.1755
63.2272
63.6692
64.0178
64.3924
64.5327
64.5401
64.9971
65.4685
66.1065
66.1444
66.1655
66.2044
66.392
66.5257
66.5326
66.569
66.578
66.6038
66.8318
66.909
67.1435
67.161
67.2411
67.33
67.3867
67.4631
67.5513
67.5651
67.5922
67.6528
67.6956
67.7141
67.8092
67.9558
67.9857
68.1951
68.3193
68.3278
68.3439
68.523
68.5335
68.5748
68.5894
68.6063
68.6161
68.6214
68.6434
68.6582
68.7522
68.7727
69.0109
69.0194
69.1408
69.1862
69.1927
69.2711
69.2989
69.3052
69.3618
69.4034
69.4634
69.6047
69.6566
69.6989
69.7409
69.7602
69.841
69.8771
69.8949
70.0261
70.2444
70.3537
70.4701
70.5197
70.6441
70.6751
70.7551
70.769
70.9303
71.1486
71

In [169]:
gal_with_dist_in_sort = gal_with_dist_final[gal_with_dist_final[:,4].argsort()]
print(gal_with_dist_in_sort)
print(len(gal_with_dist_in_sort))

[[2.5990000e+03 1.2005890e+02 4.6042600e+01 6.0000000e-04 2.7196000e+00]
 [2.0920000e+03 1.8303890e+02 3.6168900e+01 8.0000000e-04 3.2649000e+00]
 [1.1180000e+03 2.1062360e+02 5.4271000e+01 1.7000000e-03 7.1401000e+00]
 ...
 [1.3890000e+03 2.0923420e+02 4.3313500e+01 1.4990000e-01 6.4240010e+02]
 [3.0070000e+03 1.2434230e+02 2.7796200e+01 1.5020000e-01 6.4366370e+02]
 [2.7000000e+01 2.3216730e+02 4.3022700e+01 2.7820000e-01 1.1922116e+03]]
4656


In [190]:
# Number of galaxies with indices of distances

d_gal_1 = gal_with_dist_final_sort[:][100]
d_gal_2 = gal_with_dist_final_sort[:][52]
print(d_gal_1)
print(d_gal_2)

#-----for loop to count galaxies within distance interval------
count = 0
for d in gal_with_dist_final_sort[:]:
    if d_gal_2 >= d >= d_gal_1 or d_gal_1 >= d >= d_gal_2:
        count = count+1
print(count)

69.1862
64.5401
49


In [191]:
# Number of galaxies with actual distance values

d_gal_1 = 20
d_gal_2 = 1200
print(d_gal_1)
print(d_gal_2)

#-----for loop to count galaxies within distance interval------
count = 0
for d in gal_with_dist_final[:,4]:
    if d_gal_2 >= d >= d_gal_1 or d_gal_1 >= d >= d_gal_2:
        count = count+1
print(f"The number of galaxies observed by SDSS-MaNGA between {d_gal_1} Mpc and {d_gal_2} Mpc is {count}.")

20
1200
The number of galaxies observed by SDSS-MaNGA between 20 Mpc and 1200 Mpc is 4652.


---------------------------------------------------------------------------------------------------------------------------------------------

Part 3

Compute the physical separation between two galaxies, given their serial numbers. Note: The two galaxies might be at different radial distances.

In [117]:
#serial_1 = int(gal_with_dist_final[:,0][0])
#serial_2 = int(gal_with_dist_final[:,0][100])
serial_1 = 0
serial_2 = 100
alpha_1 = RA[serial_1]
print(alpha_1)
alpha_2 = RA[serial_2]
print(alpha_2)
del_1 = Dec[serial_1]
print(del_1)
del_2 = Dec[serial_2]
print(del_2)

133.3711
258.49585
57.598427
33.607136


In [118]:
def angular_separation(galaxies):
    theta = np.arccos((np.sin(del_1)*np.sin(del_2) + np.cos(del_1)*np.cos(del_2)*np.cos(alpha_1 - alpha_2)))
    #theta = np.arccos(cos_theta)
    return theta
    #return theta
ang_sep = angular_separation(galaxies)
print(f"The angular separation between the galaxies with serial numbers {serial_1} and {serial_2} is {ang_sep}.")

The angular separation between the galaxies with serial numbers 0 and 100 is 1.0958400643768713.
